### ISSUE TITLE
Loggly not found, Loggly not defined - meteor 1.4.1.1

### ISSUE THREAD

**Issue by polonski** [miktam/loggly#10]
Hi there,

After installing this and following instructions both from there and from Loggly [ https://www.loggly.com/blog/managing-a-meteor-application-in-production-three-real-log-management-use-cases ] 

using either methods throws this server side error:

```
W20161004-22:59:54.047(0)? (STDERR) Loggly not found in settings.json
W20161004-22:59:54.125(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.4.1_1.1hxvprr++os.linux.x86_64+web.browser+we
b.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161004-22:59:54.127(0)? (STDERR)                                             throw(ex);
W20161004-22:59:54.129(0)? (STDERR)                                             ^
W20161004-22:59:54.130(0)? (STDERR) 
W20161004-22:59:54.133(0)? (STDERR) ReferenceError: Loggly is not defined
W20161004-22:59:54.134(0)? (STDERR)     at server/main.js:7:15
W20161004-22:59:54.135(0)? (STDERR)     at /root/ap/.meteor/local/build/programs/server/boot.js:299:5

```

my  server main.js looks like this (with details removed):

```
import { Meteor } from 'meteor/meteor';


Meteor.startup(() => {
  // code to run on server at startup


    Logger = new Loggly({
        token: "crazy-long-token",
        subdomain: "sdomain",
        auth: {
          username: "un",
          password: "pass"
        },
        //
        // Optional: Tag to send with EVERY log message
        //
        tags: ['global-tag'],
        // Optional: logs will be stored in JSON format
        json: true
      });

    Logger.log({message:"first log from meteor"});
});

```

Putting this in settings.json as recommended in the README didn't help either - same issue.

Any help would be fantastic.

thanks

**Comment by polonski** [comment]
Also I notice you've moved the loggly settings to settings.json file

My settings.json file looks like this: (details removed_

```
{
        token: "some-long-token",
        subdomain: "sdf",
        auth: {
          username: "sdf",
          password: "sdf"
        },
        //
        // Optional: Tag to send with EVERY log message
        //
        tags: ['global-tag'],
        // Optional: logs will be stored in JSON format
        json: true
  }
```

but I get the error still:

`W20161004-23:51:24.842(0)? (STDERR) Loggly not found in settings.json`

**Comment by polonski** [comment]
ah I found the issue(s)

2 things
1. meteor has to be run to include the settings.json file from root of your app:
   `meteor --settings settings.json`
2. the settings.json file must contain the `"loggly"` attribute AND all the variables must be in double quotes:

```
{
    "loggly":{
            "token": "really-long-token",
            "subdomain": "wqer",
            "auth": {
              "username": "qwer",
              "password": "qwer"
            },
            "tags": ["global-tag"],
            "json": "true"
       } 
}
```
