### ISSUE TITLE
ReferenceError: check is not defined

### ISSUE THREAD

**Issue by trymbill** [miktam/loggly#6]
In trying to run `Logger.log("first log from meteor");` I get this error in the server console:

```
I20160908-10:01:15.519(-7)? Exception while invoking method 'logglyLog' ReferenceError: check is not defined
I20160908-10:01:15.520(-7)?     at [object Object].Meteor.methods.logglyLog (packages/miktam_loggly/logglyMeteorMethods.js:3:1)
I20160908-10:01:15.522(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160908-10:01:15.522(-7)?     at packages/ddp-server/livedata_server.js:711:19
I20160908-10:01:15.523(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160908-10:01:15.524(-7)?     at packages/ddp-server/livedata_server.js:709:40
I20160908-10:01:15.524(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160908-10:01:15.524(-7)?     at packages/ddp-server/livedata_server.js:707:46
I20160908-10:01:15.525(-7)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20160908-10:01:15.529(-7)?     at packages/ddp-server/livedata_server.js:551:43
```

**Comment by trymbill** [comment]
A simple solution is to add the check package with `$meteor add check` but I thought it might be a good idea for you to add it to your package dependencies.
